name: Build firmware

on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          apt install make gcc sdcc xxd python-is-python3 libjson-c-dev git -y

      - name: Check machine definitions
        run: make machine_check

      - name: Build firmware
        run: make MACHINE="FG_4GT_2SX_V2_0"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-nosfp
          path: output/*.bin
